/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of PixelFormat.xs. Do not edit this file, edit PixelFormat.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "lib/SDL/PixelFormat.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#ifndef aTHX_
#define aTHX_
#endif

#include <SDL.h>

#line 21 "lib/SDL/PixelFormat.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 64 "lib/SDL/PixelFormat.c"

XS(XS_SDL__PixelFormat_palette); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_palette)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
#line 34 "lib/SDL/PixelFormat.xs"
		char* CLASS = "SDL::Palette";
#line 80 "lib/SDL/PixelFormat.c"
	SDL_Palette *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 36 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->palette;
#line 92 "lib/SDL/PixelFormat.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );


    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_BitsPerPixel); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_BitsPerPixel)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint8	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 45 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->BitsPerPixel;
#line 126 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_BytesPerPixel); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_BytesPerPixel)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint8	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 53 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->BytesPerPixel;
#line 157 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_Rloss); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_Rloss)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint8	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 61 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->Rloss;
#line 188 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_Bloss); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_Bloss)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint8	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 69 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->Bloss;
#line 219 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_Gloss); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_Gloss)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint8	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 77 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->Gloss;
#line 250 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_Aloss); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_Aloss)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint8	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 85 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->Aloss;
#line 281 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_Rshift); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_Rshift)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint8	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 93 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->Rshift;
#line 312 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_Bshift); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_Bshift)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint8	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 101 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->Bshift;
#line 343 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_Gshift); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_Gshift)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint8	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 109 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->Gshift;
#line 374 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_Ashift); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_Ashift)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint8	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 117 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->Ashift;
#line 405 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_Rmask); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_Rmask)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 125 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->Rmask;
#line 436 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_Bmask); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_Bmask)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 133 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->Bmask;
#line 467 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_Gmask); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_Gmask)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 141 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->Gmask;
#line 498 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_Amask); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_Amask)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 149 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->Amask;
#line 529 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_colorkey); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_colorkey)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 157 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->colorkey;
#line 560 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__PixelFormat_alpha); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__PixelFormat_alpha)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pixelformat");
    {
	SDL_PixelFormat *	pixelformat;
	Uint8	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixelformat = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 165 "lib/SDL/PixelFormat.xs"
		RETVAL = pixelformat->alpha;
#line 591 "lib/SDL/PixelFormat.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_SDL__PixelFormat); /* prototype to pass -Wmissing-prototypes */
XS(boot_SDL__PixelFormat)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("SDL::PixelFormat::palette", XS_SDL__PixelFormat_palette, file);
        newXS("SDL::PixelFormat::BitsPerPixel", XS_SDL__PixelFormat_BitsPerPixel, file);
        newXS("SDL::PixelFormat::BytesPerPixel", XS_SDL__PixelFormat_BytesPerPixel, file);
        newXS("SDL::PixelFormat::Rloss", XS_SDL__PixelFormat_Rloss, file);
        newXS("SDL::PixelFormat::Bloss", XS_SDL__PixelFormat_Bloss, file);
        newXS("SDL::PixelFormat::Gloss", XS_SDL__PixelFormat_Gloss, file);
        newXS("SDL::PixelFormat::Aloss", XS_SDL__PixelFormat_Aloss, file);
        newXS("SDL::PixelFormat::Rshift", XS_SDL__PixelFormat_Rshift, file);
        newXS("SDL::PixelFormat::Bshift", XS_SDL__PixelFormat_Bshift, file);
        newXS("SDL::PixelFormat::Gshift", XS_SDL__PixelFormat_Gshift, file);
        newXS("SDL::PixelFormat::Ashift", XS_SDL__PixelFormat_Ashift, file);
        newXS("SDL::PixelFormat::Rmask", XS_SDL__PixelFormat_Rmask, file);
        newXS("SDL::PixelFormat::Bmask", XS_SDL__PixelFormat_Bmask, file);
        newXS("SDL::PixelFormat::Gmask", XS_SDL__PixelFormat_Gmask, file);
        newXS("SDL::PixelFormat::Amask", XS_SDL__PixelFormat_Amask, file);
        newXS("SDL::PixelFormat::colorkey", XS_SDL__PixelFormat_colorkey, file);
        newXS("SDL::PixelFormat::alpha", XS_SDL__PixelFormat_alpha, file);

    /* Initialisation Section */

#if XSubPPtmpAAAA
#if XSubPPtmpAAAB
#endif
#if XSubPPtmpAAAC
#endif
#if XSubPPtmpAAAD
#endif
#if XSubPPtmpAAAE
#endif
#endif
#if XSubPPtmpAAAF
#if XSubPPtmpAAAG
#endif
#if XSubPPtmpAAAH
#endif
#if XSubPPtmpAAAI
#endif
#if XSubPPtmpAAAJ
#endif
#if XSubPPtmpAAAK
#endif
#if XSubPPtmpAAAL
#endif
#if XSubPPtmpAAAM
#endif
#if XSubPPtmpAAAN
#endif
#if XSubPPtmpAAAO
#endif
#if XSubPPtmpAAAP
#endif
#if XSubPPtmpAAAQ
#endif
#endif
#if XSubPPtmpAAAA
#endif
#if XSubPPtmpAAAB
#endif
#if XSubPPtmpAAAC
#endif
#if XSubPPtmpAAAD
#endif
#if XSubPPtmpAAAE
#endif
#if XSubPPtmpAAAF
#endif
#if XSubPPtmpAAAG
#endif
#if XSubPPtmpAAAH
#endif
#if XSubPPtmpAAAA
#endif
#line 686 "lib/SDL/PixelFormat.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

