/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of Surface.xs. Do not edit this file, edit Surface.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "lib/SDL/Surface.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#ifndef aTHX_
#define aTHX_
#endif

#include <SDL.h>

#line 21 "lib/SDL/Surface.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 64 "lib/SDL/Surface.c"

XS(XS_SDL__Surface_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Surface_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 9)
       croak_xs_usage(cv,  "CLASS, flags, width, height, depth, Rmask, Gmask, Bmask, Amask");
    {
	char*	CLASS = (char *)SvPV_nolen(ST(0));
	Uint32	flags = (Uint32)SvUV(ST(1));
	int	width = (int)SvIV(ST(2));
	int	height = (int)SvIV(ST(3));
	int	depth = (int)SvIV(ST(4));
	Uint32	Rmask = (Uint32)SvUV(ST(5));
	Uint32	Gmask = (Uint32)SvUV(ST(6));
	Uint32	Bmask = (Uint32)SvUV(ST(7));
	Uint32	Amask = (Uint32)SvUV(ST(8));
	SDL_Surface *	RETVAL;
#line 43 "lib/SDL/Surface.xs"
		RETVAL = SDL_CreateRGBSurface ( flags, width, height,
				depth, Rmask, Gmask, Bmask, Amask );
#line 90 "lib/SDL/Surface.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );


    }
    XSRETURN(1);
}


XS(XS_SDL__Surface_new_from); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Surface_new_from)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 10)
       croak_xs_usage(cv,  "CLASS, pixels, width, height, depth, pitch, Rmask, Gmask, Bmask, Amask");
    {
	char*	CLASS = (char *)SvPV_nolen(ST(0));
	int	width = (int)SvIV(ST(2));
	int	height = (int)SvIV(ST(3));
	int	depth = (int)SvIV(ST(4));
	int	pitch = (int)SvIV(ST(5));
	Uint32	Rmask = (Uint32)SvUV(ST(6));
	Uint32	Gmask = (Uint32)SvUV(ST(7));
	Uint32	Bmask = (Uint32)SvUV(ST(8));
	Uint32	Amask = (Uint32)SvUV(ST(9));
	IV	pixels = (IV)SvIV(ST(1));
	SDL_Surface *	RETVAL;
#line 61 "lib/SDL/Surface.xs"
		warn ("USING THIS WILL CAUSE YOUR CODE TO SEGFAULT ON EXIT! \n READ: http://sdlperl.ath.cx/projects/SDLPerl/ticket/53");
		void *p = INT2PTR(void*, pixels);
		RETVAL = SDL_CreateRGBSurfaceFrom ( p, width, height, depth, pitch, Rmask, Gmask, Bmask, Amask );
		if( RETVAL == NULL)
		croak ("SDL_CreateRGBSurfaceFrom failed: %s", SDL_GetError());

#line 129 "lib/SDL/Surface.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );


    }
    XSRETURN(1);
}


XS(XS_SDL__Surface_format); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Surface_format)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "surface");
    {
	SDL_Surface *	surface;
#line 75 "lib/SDL/Surface.xs"
		char* CLASS = "SDL::PixelFormat";
#line 153 "lib/SDL/Surface.c"
	SDL_PixelFormat *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 77 "lib/SDL/Surface.xs"
		RETVAL = surface->format;
#line 165 "lib/SDL/Surface.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );


    }
    XSRETURN(1);
}


XS(XS_SDL__Surface_pitch); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Surface_pitch)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "surface");
    {
	SDL_Surface *	surface;
	Uint16	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 85 "lib/SDL/Surface.xs"
		RETVAL = surface->pitch;
#line 199 "lib/SDL/Surface.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Surface_w); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Surface_w)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "surface");
    {
	SDL_Surface *	surface;
	Uint16	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 93 "lib/SDL/Surface.xs"
		RETVAL = surface->w;
#line 230 "lib/SDL/Surface.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Surface_h); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Surface_h)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "surface");
    {
	SDL_Surface *	surface;
	Uint16	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 101 "lib/SDL/Surface.xs"
		RETVAL = surface->h;
#line 261 "lib/SDL/Surface.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Surface_get_pixels); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Surface_get_pixels)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "surface");
    {
	SDL_Surface *	surface;
	IV	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 109 "lib/SDL/Surface.xs"
	  if(!surface->pixels) croak("Incomplete surface");
	  RETVAL = PTR2IV(surface->pixels);
#line 293 "lib/SDL/Surface.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Surface_set_pixels); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Surface_set_pixels)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "surface, pixels");
    {
	SDL_Surface *	surface;
	SV *	pixels = ST(1);
#line 121 "lib/SDL/Surface.xs"
	  STRLEN len;
	  void *p;

#line 317 "lib/SDL/Surface.c"

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 125 "lib/SDL/Surface.xs"
	  p = SvPV(pixels, len);
	  if (len > surface->pitch*surface->h)
		len = surface->pitch*surface->h;
	  memcpy(surface->pixels, p, len);
#line 331 "lib/SDL/Surface.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_SDL__Surface_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Surface_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "surface");
    {
	SDL_Surface *	surface;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 135 "lib/SDL/Surface.xs"
		Uint8* pixels = surface->pixels;
		Uint32 flags = surface->flags;
		SDL_FreeSurface(surface);
		if (flags & SDL_PREALLOC)
			Safefree(pixels);
#line 363 "lib/SDL/Surface.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_SDL__Surface); /* prototype to pass -Wmissing-prototypes */
XS(boot_SDL__Surface)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("SDL::Surface::new", XS_SDL__Surface_new, file);
        newXS("SDL::Surface::new_from", XS_SDL__Surface_new_from, file);
        newXS("SDL::Surface::format", XS_SDL__Surface_format, file);
        newXS("SDL::Surface::pitch", XS_SDL__Surface_pitch, file);
        newXS("SDL::Surface::w", XS_SDL__Surface_w, file);
        newXS("SDL::Surface::h", XS_SDL__Surface_h, file);
        newXS("SDL::Surface::get_pixels", XS_SDL__Surface_get_pixels, file);
        newXS("SDL::Surface::set_pixels", XS_SDL__Surface_set_pixels, file);
        newXS("SDL::Surface::DESTROY", XS_SDL__Surface_DESTROY, file);

    /* Initialisation Section */

#if XSubPPtmpAAAA
#if XSubPPtmpAAAB
#endif
#if XSubPPtmpAAAC
#endif
#if XSubPPtmpAAAD
#endif
#if XSubPPtmpAAAE
#endif
#endif
#if XSubPPtmpAAAF
#if XSubPPtmpAAAG
#endif
#if XSubPPtmpAAAH
#endif
#if XSubPPtmpAAAI
#endif
#if XSubPPtmpAAAJ
#endif
#if XSubPPtmpAAAK
#endif
#if XSubPPtmpAAAL
#endif
#if XSubPPtmpAAAM
#endif
#if XSubPPtmpAAAN
#endif
#if XSubPPtmpAAAO
#endif
#if XSubPPtmpAAAP
#endif
#if XSubPPtmpAAAQ
#endif
#endif
#line 431 "lib/SDL/Surface.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

