/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of VideoInfo.xs. Do not edit this file, edit VideoInfo.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "lib/SDL/VideoInfo.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#ifndef aTHX_
#define aTHX_
#endif

#include <SDL.h>

#line 21 "lib/SDL/VideoInfo.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 64 "lib/SDL/VideoInfo.c"

XS(XS_SDL__VideoInfo_hw_available); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__VideoInfo_hw_available)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "videoinfo");
    {
	SDL_VideoInfo *	videoinfo;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ videoinfo = (SDL_VideoInfo *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 43 "lib/SDL/VideoInfo.xs"
		RETVAL = videoinfo->hw_available;
#line 90 "lib/SDL/VideoInfo.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__VideoInfo_wm_available); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__VideoInfo_wm_available)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "videoinfo");
    {
	SDL_VideoInfo *	videoinfo;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ videoinfo = (SDL_VideoInfo *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 53 "lib/SDL/VideoInfo.xs"
		RETVAL = videoinfo->wm_available;
#line 121 "lib/SDL/VideoInfo.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__VideoInfo_blit_hw); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__VideoInfo_blit_hw)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "videoinfo");
    {
	SDL_VideoInfo *	videoinfo;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ videoinfo = (SDL_VideoInfo *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 63 "lib/SDL/VideoInfo.xs"
		RETVAL = videoinfo->blit_hw;
#line 152 "lib/SDL/VideoInfo.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__VideoInfo_blit_hw_CC); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__VideoInfo_blit_hw_CC)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "videoinfo");
    {
	SDL_VideoInfo *	videoinfo;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ videoinfo = (SDL_VideoInfo *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 73 "lib/SDL/VideoInfo.xs"
		RETVAL = videoinfo->blit_hw_CC;
#line 183 "lib/SDL/VideoInfo.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__VideoInfo_blit_hw_A); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__VideoInfo_blit_hw_A)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "videoinfo");
    {
	SDL_VideoInfo *	videoinfo;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ videoinfo = (SDL_VideoInfo *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 84 "lib/SDL/VideoInfo.xs"
		RETVAL = videoinfo->blit_hw_A;
#line 214 "lib/SDL/VideoInfo.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__VideoInfo_blit_sw); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__VideoInfo_blit_sw)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "videoinfo");
    {
	SDL_VideoInfo *	videoinfo;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ videoinfo = (SDL_VideoInfo *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 94 "lib/SDL/VideoInfo.xs"
		RETVAL = videoinfo->blit_sw;
#line 245 "lib/SDL/VideoInfo.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__VideoInfo_blit_sw_CC); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__VideoInfo_blit_sw_CC)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "videoinfo");
    {
	SDL_VideoInfo *	videoinfo;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ videoinfo = (SDL_VideoInfo *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 104 "lib/SDL/VideoInfo.xs"
		RETVAL = videoinfo->blit_sw_CC;
#line 276 "lib/SDL/VideoInfo.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__VideoInfo_blit_sw_A); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__VideoInfo_blit_sw_A)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "videoinfo");
    {
	SDL_VideoInfo *	videoinfo;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ videoinfo = (SDL_VideoInfo *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 115 "lib/SDL/VideoInfo.xs"
		RETVAL = videoinfo->blit_sw_A;
#line 307 "lib/SDL/VideoInfo.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__VideoInfo_blit_fill); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__VideoInfo_blit_fill)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "videoinfo");
    {
	SDL_VideoInfo *	videoinfo;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ videoinfo = (SDL_VideoInfo *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 125 "lib/SDL/VideoInfo.xs"
		RETVAL = videoinfo->blit_fill;
#line 338 "lib/SDL/VideoInfo.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__VideoInfo_video_mem); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__VideoInfo_video_mem)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "videoinfo");
    {
	SDL_VideoInfo *	videoinfo;
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ videoinfo = (SDL_VideoInfo *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 135 "lib/SDL/VideoInfo.xs"
		RETVAL = videoinfo->video_mem;
#line 369 "lib/SDL/VideoInfo.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__VideoInfo_vfmt); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__VideoInfo_vfmt)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "videoinfo");
    {
	SDL_VideoInfo *	videoinfo;
#line 147 "lib/SDL/VideoInfo.xs"
		char* CLASS = "SDL::VideoFormat";	

#line 391 "lib/SDL/VideoInfo.c"
	SDL_PixelFormat *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ videoinfo = (SDL_VideoInfo *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 150 "lib/SDL/VideoInfo.xs"
		RETVAL = videoinfo->vfmt;
#line 403 "lib/SDL/VideoInfo.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );


    }
    XSRETURN(1);
}


XS(XS_SDL__VideoInfo_current_w); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__VideoInfo_current_w)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "videoinfo");
    {
	SDL_VideoInfo *	videoinfo;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ videoinfo = (SDL_VideoInfo *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 160 "lib/SDL/VideoInfo.xs"
		RETVAL = videoinfo->current_w;
#line 437 "lib/SDL/VideoInfo.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__VideoInfo_current_h); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__VideoInfo_current_h)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "videoinfo");
    {
	SDL_VideoInfo *	videoinfo;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ videoinfo = (SDL_VideoInfo *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 170 "lib/SDL/VideoInfo.xs"
		RETVAL = videoinfo->current_h;
#line 468 "lib/SDL/VideoInfo.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_SDL__VideoInfo); /* prototype to pass -Wmissing-prototypes */
XS(boot_SDL__VideoInfo)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("SDL::VideoInfo::hw_available", XS_SDL__VideoInfo_hw_available, file);
        newXS("SDL::VideoInfo::wm_available", XS_SDL__VideoInfo_wm_available, file);
        newXS("SDL::VideoInfo::blit_hw", XS_SDL__VideoInfo_blit_hw, file);
        newXS("SDL::VideoInfo::blit_hw_CC", XS_SDL__VideoInfo_blit_hw_CC, file);
        newXS("SDL::VideoInfo::blit_hw_A", XS_SDL__VideoInfo_blit_hw_A, file);
        newXS("SDL::VideoInfo::blit_sw", XS_SDL__VideoInfo_blit_sw, file);
        newXS("SDL::VideoInfo::blit_sw_CC", XS_SDL__VideoInfo_blit_sw_CC, file);
        newXS("SDL::VideoInfo::blit_sw_A", XS_SDL__VideoInfo_blit_sw_A, file);
        newXS("SDL::VideoInfo::blit_fill", XS_SDL__VideoInfo_blit_fill, file);
        newXS("SDL::VideoInfo::video_mem", XS_SDL__VideoInfo_video_mem, file);
        newXS("SDL::VideoInfo::vfmt", XS_SDL__VideoInfo_vfmt, file);
        newXS("SDL::VideoInfo::current_w", XS_SDL__VideoInfo_current_w, file);
        newXS("SDL::VideoInfo::current_h", XS_SDL__VideoInfo_current_h, file);

    /* Initialisation Section */

#if XSubPPtmpAAAA
#if XSubPPtmpAAAB
#endif
#if XSubPPtmpAAAC
#endif
#if XSubPPtmpAAAD
#endif
#if XSubPPtmpAAAE
#endif
#endif
#if XSubPPtmpAAAF
#if XSubPPtmpAAAG
#endif
#if XSubPPtmpAAAH
#endif
#if XSubPPtmpAAAI
#endif
#if XSubPPtmpAAAJ
#endif
#if XSubPPtmpAAAK
#endif
#if XSubPPtmpAAAL
#endif
#if XSubPPtmpAAAM
#endif
#if XSubPPtmpAAAN
#endif
#if XSubPPtmpAAAO
#endif
#if XSubPPtmpAAAP
#endif
#if XSubPPtmpAAAQ
#endif
#endif
#line 541 "lib/SDL/VideoInfo.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

