/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of Video.xs. Do not edit this file, edit Video.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "lib/SDL/Video.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#ifndef aTHX_
#define aTHX_
#endif

#include <SDL.h>


static Uint16* av_to_uint16 (AV* av)
{
	int len = av_len(av);
	if( len != -1)
	{
	int i;
	Uint16* table = (Uint16 *)safemalloc(sizeof(Uint16)*(len));
	for ( i = 0; i < len+1 ; i++ ){ 
		SV ** temp = av_fetch(av,i,0);
	      if( temp != NULL)
		{
			table[i] =  (Uint16 *) SvIV(  *temp   );
		}
		else { table[i] =0; }

	}
	return table;
	}
	return NULL;
}



#line 45 "lib/SDL/Video.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 88 "lib/SDL/Video.c"

XS(XS_SDL__Video_get_video_surface); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_get_video_surface)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 50 "lib/SDL/Video.xs"
		char* CLASS = "SDL::Surface";
#line 103 "lib/SDL/Video.c"
	SDL_Surface *	RETVAL;
#line 52 "lib/SDL/Video.xs"
		RETVAL = SDL_GetVideoSurface();
#line 107 "lib/SDL/Video.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );


    }
    XSRETURN(1);
}


XS(XS_SDL__Video_get_video_info); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_get_video_info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 60 "lib/SDL/Video.xs"
		char* CLASS = "SDL::VideoInfo";
#line 130 "lib/SDL/Video.c"
	SDL_VideoInfo *	RETVAL;
#line 62 "lib/SDL/Video.xs"
		RETVAL = (SDL_VideoInfo *) SDL_GetVideoInfo();

#line 135 "lib/SDL/Video.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );


    }
    XSRETURN(1);
}


XS(XS_SDL__Video_video_driver_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_video_driver_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	SV *	RETVAL;
#line 71 "lib/SDL/Video.xs"
		char buffer[1024];
		if ( SDL_VideoDriverName(buffer, 1024) != NULL ) 
		{ 
			RETVAL =  newSVpv(buffer, 0);
		} 
		else 
			 XSRETURN_UNDEF;  	
#line 165 "lib/SDL/Video.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_list_modes); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_list_modes)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "format, flags");
    {
	Uint32	flags = (Uint32)SvUV(ST(1));
	SDL_PixelFormat *	format;
	AV *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ format = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 87 "lib/SDL/Video.xs"
		SDL_Rect **mode;
		RETVAL = newAV();
		mode = SDL_ListModes(format,flags);
		if (mode == (SDL_Rect**)-1 ) {
			av_push(RETVAL,newSVpv("all",0));
		} else if (! mode ) {
			av_push(RETVAL,newSVpv("none",0));
		} else {
			for (;*mode;mode++) {
				av_push(RETVAL,newSViv(PTR2IV(*mode)));
			}
		}
#line 208 "lib/SDL/Video.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_video_mode_ok); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_video_mode_ok)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "width, height, bpp, flags");
    {
	int	width = (int)SvIV(ST(0));
	int	height = (int)SvIV(ST(1));
	int	bpp = (int)SvIV(ST(2));
	Uint32	flags = (Uint32)SvUV(ST(3));
	int	RETVAL;
	dXSTARG;
#line 110 "lib/SDL/Video.xs"
		RETVAL = SDL_VideoModeOK(width,height,bpp,flags);
#line 235 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_set_video_mode); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_set_video_mode)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "width, height, bpp, flags");
    {
	int	width = (int)SvIV(ST(0));
	int	height = (int)SvIV(ST(1));
	int	bpp = (int)SvIV(ST(2));
	Uint32	flags = (Uint32)SvUV(ST(3));
#line 122 "lib/SDL/Video.xs"
		char* CLASS = "SDL::Surface";
#line 259 "lib/SDL/Video.c"
	SDL_Surface *	RETVAL;
#line 124 "lib/SDL/Video.xs"
		RETVAL = SDL_SetVideoMode(width,height,bpp,flags);
#line 263 "lib/SDL/Video.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );


    }
    XSRETURN(1);
}


XS(XS_SDL__Video_update_rect); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_update_rect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "surface, x, y, w, h");
    {
	SDL_Surface *	surface;
	int	x = (int)SvIV(ST(1));
	int	y = (int)SvIV(ST(2));
	int	w = (int)SvIV(ST(3));
	int	h = (int)SvIV(ST(4));

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 137 "lib/SDL/Video.xs"
		SDL_UpdateRect(surface,x,y,w,h);
#line 299 "lib/SDL/Video.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_SDL__Video_update_rects); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_update_rects)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "surface, ...");
    {
	SDL_Surface *	surface;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 143 "lib/SDL/Video.xs"
		SDL_Rect *rects;
		int num_rects,i;
		if ( items < 2 ) return;
		num_rects = items - 1;
		rects = (SDL_Rect *)safemalloc(sizeof(SDL_Rect)*items);
		for(i=0;i<num_rects;i++) {
			rects[i] = *(SDL_Rect *)SvIV((SV*)SvRV( ST(i + 1) ));
		}
		SDL_UpdateRects(surface,num_rects,rects);
		safefree(rects);
#line 336 "lib/SDL/Video.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_SDL__Video_flip); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_flip)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "surface");
    {
	SDL_Surface *	surface;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 159 "lib/SDL/Video.xs"
		RETVAL = SDL_Flip(surface);
#line 366 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_set_colors); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_set_colors)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2)
       croak_xs_usage(cv,  "surface, start, ...");
    {
	SDL_Surface *	surface;
	int	start = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 168 "lib/SDL/Video.xs"
		SDL_Color *colors,*temp;
		int i, length;
		if ( items < 3 ) { RETVAL = 0;}
		else
		{
		length = items - 2;
		colors = (SDL_Color *)safemalloc(sizeof(SDL_Color)*(length+1));
		for ( i = 0; i < length ; i++ ) {
			temp = (SDL_Color *)SvIV(ST(i+2));
			colors[i].r = temp->r;
			colors[i].g = temp->g;
			colors[i].b = temp->b;
		}
		RETVAL = SDL_SetColors(surface, colors, start, length );
	  	safefree(colors);
		}	

#line 414 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_set_palette); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_set_palette)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 3)
       croak_xs_usage(cv,  "surface, flags, start, ...");
    {
	SDL_Surface *	surface;
	int	flags = (int)SvIV(ST(1));
	int	start = (int)SvIV(ST(2));
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 195 "lib/SDL/Video.xs"
		SDL_Color *colors,*temp;
		int i, length;
		if ( items < 4 ) { 
		RETVAL = 0;
			}
		else
		{		
		length = items - 3;
		colors = (SDL_Color *)safemalloc(sizeof(SDL_Color)*(length+1));
		for ( i = 0; i < length ; i++ ){ 
			temp = (SDL_Color *)SvIV(ST(i+3));
			colors[i].r = temp->r;
			colors[i].g = temp->g;
			colors[i].b = temp->b;
		}
		RETVAL = SDL_SetPalette(surface, flags, colors, start, length );
	  	safefree(colors);
		}
#line 464 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_set_gamma); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_set_gamma)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "r, g, b");
    {
	float	r = (float)SvNV(ST(0));
	float	g = (float)SvNV(ST(1));
	float	b = (float)SvNV(ST(2));
	int	RETVAL;
	dXSTARG;
#line 222 "lib/SDL/Video.xs"
		RETVAL = SDL_SetGamma(r,g,b);
#line 489 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_set_gamma_ramp); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_set_gamma_ramp)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "rt, gt, bt");
    {
	AV*	rt;
	AV*	gt;
	AV*	bt;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && SvTYPE(SvRV(ST(0)))==SVt_PVAV)
	    rt = (AV*)SvRV(ST(0));
	else
	    Perl_croak(aTHX_ "%s: %s is not an array reference",
			"SDL::Video::set_gamma_ramp",
			"rt");

	if (SvROK(ST(1)) && SvTYPE(SvRV(ST(1)))==SVt_PVAV)
	    gt = (AV*)SvRV(ST(1));
	else
	    Perl_croak(aTHX_ "%s: %s is not an array reference",
			"SDL::Video::set_gamma_ramp",
			"gt");

	if (SvROK(ST(2)) && SvTYPE(SvRV(ST(2)))==SVt_PVAV)
	    bt = (AV*)SvRV(ST(2));
	else
	    Perl_croak(aTHX_ "%s: %s is not an array reference",
			"SDL::Video::set_gamma_ramp",
			"bt");
#line 233 "lib/SDL/Video.xs"
		Uint16 *redtable, *greentable, *bluetable;
		redtable = av_to_uint16(rt);
		greentable = av_to_uint16(gt);
		bluetable = av_to_uint16(bt);
		RETVAL =  SDL_SetGammaRamp(redtable, greentable, bluetable);
		if( redtable != NULL) { safefree(redtable); }
		if( greentable != NULL) { safefree(greentable); }
		if( bluetable != NULL) { safefree(bluetable); }	
#line 542 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_map_RGB); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_map_RGB)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "pixel_format, r, g, b");
    {
	SDL_PixelFormat *	pixel_format;
	Uint8	r = (unsigned char)SvUV(ST(1));
	Uint8	g = (unsigned char)SvUV(ST(2));
	Uint8	b = (unsigned char)SvUV(ST(3));
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixel_format = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 253 "lib/SDL/Video.xs"
		RETVAL = SDL_MapRGB(pixel_format,r,g,b);
#line 576 "lib/SDL/Video.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_map_RGBA); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_map_RGBA)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "pixel_format, r, g, b, a");
    {
	SDL_PixelFormat *	pixel_format;
	Uint8	r = (unsigned char)SvUV(ST(1));
	Uint8	g = (unsigned char)SvUV(ST(2));
	Uint8	b = (unsigned char)SvUV(ST(3));
	Uint8	a = (unsigned char)SvUV(ST(4));
	Uint32	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixel_format = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 265 "lib/SDL/Video.xs"
		RETVAL = SDL_MapRGBA(pixel_format,r,g,b,a);
#line 611 "lib/SDL/Video.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_lock_surface); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_lock_surface)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "surface");
    {
	SDL_Surface *	surface;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 273 "lib/SDL/Video.xs"
		RETVAL = SDL_LockSurface(surface);
#line 642 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_unlock_surface); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_unlock_surface)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "surface");
    {
	SDL_Surface *	surface;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 281 "lib/SDL/Video.xs"
		SDL_UnlockSurface(surface);
#line 671 "lib/SDL/Video.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_SDL__Video_convert_surface); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_convert_surface)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "src, fmt, flags");
    {
	SDL_Surface*	src;
	SDL_PixelFormat*	fmt;
	Uint32	flags = (Uint32)SvUV(ST(2));
#line 290 "lib/SDL/Video.xs"
		char *CLASS = "SDL::Surface";
#line 693 "lib/SDL/Video.c"
	SDL_Surface *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ src = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) )
		{ fmt = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(1) )); }
	else if (ST(1) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 292 "lib/SDL/Video.xs"
		RETVAL = SDL_ConvertSurface(src, fmt, flags);
#line 713 "lib/SDL/Video.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );


    }
    XSRETURN(1);
}


XS(XS_SDL__Video_display_format); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_display_format)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "surface");
    {
	SDL_Surface *	surface;
#line 301 "lib/SDL/Video.xs"
		char* CLASS = "SDL::Surface";
#line 737 "lib/SDL/Video.c"
	SDL_Surface *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 303 "lib/SDL/Video.xs"
		RETVAL = SDL_DisplayFormat(surface);
#line 749 "lib/SDL/Video.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );


    }
    XSRETURN(1);
}


XS(XS_SDL__Video_display_format_alpha); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_display_format_alpha)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "surface");
    {
	SDL_Surface *	surface;
#line 311 "lib/SDL/Video.xs"
		char* CLASS = "SDL::Surface";
#line 773 "lib/SDL/Video.c"
	SDL_Surface *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 313 "lib/SDL/Video.xs"
		RETVAL = SDL_DisplayFormatAlpha(surface);
#line 785 "lib/SDL/Video.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );


    }
    XSRETURN(1);
}


XS(XS_SDL__Video_set_color_key); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_set_color_key)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "surface, flag, key");
    {
	SDL_Surface *	surface;
	Uint32	flag = (Uint32)SvUV(ST(1));
	SDL_Color *	key;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(2)) && (SvTYPE(SvRV(ST(2))) == SVt_PVMG) )
		{ key = (SDL_Color *)SvIV((SV*)SvRV( ST(2) )); }
	else if (ST(2) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 324 "lib/SDL/Video.xs"
		Uint32 pixel = SDL_MapRGB(surface->format,key->r,key->g,key->b);
		RETVAL = SDL_SetColorKey(surface,flag,pixel);
#line 830 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_set_alpha); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_set_alpha)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "surface, flag, alpha");
    {
	SDL_Surface *	surface;
	Uint32	flag = (Uint32)SvUV(ST(1));
	Uint8	alpha = (unsigned char)SvUV(ST(2));
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 335 "lib/SDL/Video.xs"
		RETVAL = SDL_SetAlpha(surface,flag,alpha);
#line 863 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_get_RGB); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_get_RGB)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "pixel_format, pixel");
    {
	SDL_PixelFormat *	pixel_format;
	Uint32	pixel = (Uint32)SvUV(ST(1));
	AV *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixel_format = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 344 "lib/SDL/Video.xs"
		Uint8 r,g,b;
		SDL_GetRGB(pixel,pixel_format,&r,&g,&b);
		RETVAL = newAV();
		av_push(RETVAL,newSViv(r));
		av_push(RETVAL,newSViv(g));
		av_push(RETVAL,newSViv(b));
#line 899 "lib/SDL/Video.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_get_RGBA); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_get_RGBA)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "pixel_format, pixel");
    {
	SDL_PixelFormat *	pixel_format;
	Uint32	pixel = (Uint32)SvUV(ST(1));
	AV *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ pixel_format = (SDL_PixelFormat *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 358 "lib/SDL/Video.xs"
		Uint8 r,g,b,a;
		SDL_GetRGBA(pixel,pixel_format,&r,&g,&b,&a);
		RETVAL = newAV();
		av_push(RETVAL,newSViv(r));
		av_push(RETVAL,newSViv(g));
		av_push(RETVAL,newSViv(b));
		av_push(RETVAL,newSViv(a));
#line 937 "lib/SDL/Video.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_load_BMP); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_load_BMP)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "filename");
    {
	char *	filename = (char *)SvPV_nolen(ST(0));
#line 372 "lib/SDL/Video.xs"
		char* CLASS = "SDL::Surface";
#line 959 "lib/SDL/Video.c"
	SDL_Surface *	RETVAL;
#line 374 "lib/SDL/Video.xs"
		RETVAL = SDL_LoadBMP(filename);
#line 963 "lib/SDL/Video.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );


    }
    XSRETURN(1);
}


XS(XS_SDL__Video_save_BMP); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_save_BMP)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "surface, filename");
    {
	SDL_Surface *	surface;
	char *	filename = (char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 383 "lib/SDL/Video.xs"
		RETVAL = SDL_SaveBMP(surface,filename);
#line 998 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_fill_rect); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_fill_rect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "dest, dest_rect, pixel");
    {
	SDL_Surface *	dest;
	SDL_Rect *	dest_rect;
	Uint32	pixel = (Uint32)SvUV(ST(2));
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ dest = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) )
		{ dest_rect = (SDL_Rect *)SvIV((SV*)SvRV( ST(1) )); }
	else if (ST(1) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 393 "lib/SDL/Video.xs"
		RETVAL = SDL_FillRect(dest,dest_rect,pixel);
#line 1039 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_blit_surface); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_blit_surface)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "src, src_rect, dest, dest_rect");
    {
	SDL_Surface *	src;
	SDL_Surface *	dest;
	SDL_Rect *	src_rect;
	SDL_Rect *	dest_rect;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ src = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(2)) && (SvTYPE(SvRV(ST(2))) == SVt_PVMG) )
		{ dest = (SDL_Surface *)SvIV((SV*)SvRV( ST(2) )); }
	else if (ST(2) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) )
		{ src_rect = (SDL_Rect *)SvIV((SV*)SvRV( ST(1) )); }
	else if (ST(1) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(3)) && (SvTYPE(SvRV(ST(3))) == SVt_PVMG) )
		{ dest_rect = (SDL_Rect *)SvIV((SV*)SvRV( ST(3) )); }
	else if (ST(3) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 404 "lib/SDL/Video.xs"
		RETVAL = SDL_BlitSurface(src,src_rect,dest,dest_rect);
#line 1097 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_set_clip_rect); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_set_clip_rect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "surface, rect");
    {
	SDL_Surface *	surface;
	SDL_Rect *	rect;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) )
		{ rect = (SDL_Rect *)SvIV((SV*)SvRV( ST(1) )); }
	else if (ST(1) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 413 "lib/SDL/Video.xs"
		SDL_SetClipRect(surface,rect);
#line 1135 "lib/SDL/Video.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_SDL__Video_get_clip_rect); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_get_clip_rect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "surface, rect");
    {
	SDL_Surface *	surface;
	SDL_Rect *	rect;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ surface = (SDL_Surface *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) )
		{ rect = (SDL_Rect *)SvIV((SV*)SvRV( ST(1) )); }
	else if (ST(1) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 420 "lib/SDL/Video.xs"
		SDL_GetClipRect(surface, rect);
#line 1172 "lib/SDL/Video.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_SDL__Video_lock_YUV_overlay); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_lock_YUV_overlay)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "overlay");
    {
	SDL_Overlay *	overlay;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ overlay = (SDL_Overlay *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 428 "lib/SDL/Video.xs"
		RETVAL = SDL_LockYUVOverlay(overlay);
#line 1202 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_unlock_YUV_overlay); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_unlock_YUV_overlay)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "overlay");
    {
	SDL_Overlay *	overlay;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ overlay = (SDL_Overlay *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 436 "lib/SDL/Video.xs"
                SDL_UnlockYUVOverlay(overlay);
#line 1231 "lib/SDL/Video.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_SDL__Video_display_YUV_overlay); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_display_YUV_overlay)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "overlay, dstrect");
    {
	SDL_Overlay *	overlay;
	SDL_Rect *	dstrect;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		{ overlay = (SDL_Overlay *)SvIV((SV*)SvRV( ST(0) )); }
	else if (ST(0) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG) )
		{ dstrect = (SDL_Rect *)SvIV((SV*)SvRV( ST(1) )); }
	else if (ST(1) == 0)
	{ XSRETURN(0); }
	else{
		XSRETURN_UNDEF;
	};
#line 443 "lib/SDL/Video.xs"
		RETVAL = SDL_DisplayYUVOverlay ( overlay, dstrect );
#line 1270 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_GL_load_library); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_GL_load_library)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "path");
    {
	char *	path = (char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;
#line 452 "lib/SDL/Video.xs"
		RETVAL = SDL_GL_LoadLibrary(path);
#line 1293 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_GL_get_proc_address); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_GL_get_proc_address)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "proc");
    {
	char *	proc = (char *)SvPV_nolen(ST(0));
	void *	RETVAL;
	dXSTARG;
#line 460 "lib/SDL/Video.xs"
		RETVAL = SDL_GL_GetProcAddress(proc);
#line 1316 "lib/SDL/Video.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_GL_set_attribute); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_GL_set_attribute)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "attr, value");
    {
	int	attr = (int)SvIV(ST(0));
	int	value = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 469 "lib/SDL/Video.xs"
		RETVAL = SDL_GL_SetAttribute(attr, value);
#line 1340 "lib/SDL/Video.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_GL_get_attribute); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_GL_get_attribute)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "attr");
    {
	int	attr = (int)SvIV(ST(0));
	AV *	RETVAL;
#line 477 "lib/SDL/Video.xs"
		int value;
		RETVAL = newAV();
		av_push(RETVAL,newSViv(SDL_GL_GetAttribute(attr, &value)));
		av_push(RETVAL,newSViv(value));
#line 1365 "lib/SDL/Video.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SDL__Video_GL_swap_buffers); /* prototype to pass -Wmissing-prototypes */
XS(XS_SDL__Video_GL_swap_buffers)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 487 "lib/SDL/Video.xs"
		SDL_GL_SwapBuffers ();
#line 1386 "lib/SDL/Video.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_SDL__Video); /* prototype to pass -Wmissing-prototypes */
XS(boot_SDL__Video)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("SDL::Video::get_video_surface", XS_SDL__Video_get_video_surface, file);
        newXS("SDL::Video::get_video_info", XS_SDL__Video_get_video_info, file);
        newXS("SDL::Video::video_driver_name", XS_SDL__Video_video_driver_name, file);
        newXS("SDL::Video::list_modes", XS_SDL__Video_list_modes, file);
        newXS("SDL::Video::video_mode_ok", XS_SDL__Video_video_mode_ok, file);
        newXS("SDL::Video::set_video_mode", XS_SDL__Video_set_video_mode, file);
        newXS("SDL::Video::update_rect", XS_SDL__Video_update_rect, file);
        newXS("SDL::Video::update_rects", XS_SDL__Video_update_rects, file);
        newXS("SDL::Video::flip", XS_SDL__Video_flip, file);
        newXS("SDL::Video::set_colors", XS_SDL__Video_set_colors, file);
        newXS("SDL::Video::set_palette", XS_SDL__Video_set_palette, file);
        newXS("SDL::Video::set_gamma", XS_SDL__Video_set_gamma, file);
        newXS("SDL::Video::set_gamma_ramp", XS_SDL__Video_set_gamma_ramp, file);
        newXS("SDL::Video::map_RGB", XS_SDL__Video_map_RGB, file);
        newXS("SDL::Video::map_RGBA", XS_SDL__Video_map_RGBA, file);
        newXS("SDL::Video::lock_surface", XS_SDL__Video_lock_surface, file);
        newXS("SDL::Video::unlock_surface", XS_SDL__Video_unlock_surface, file);
        newXS("SDL::Video::convert_surface", XS_SDL__Video_convert_surface, file);
        newXS("SDL::Video::display_format", XS_SDL__Video_display_format, file);
        newXS("SDL::Video::display_format_alpha", XS_SDL__Video_display_format_alpha, file);
        newXS("SDL::Video::set_color_key", XS_SDL__Video_set_color_key, file);
        newXS("SDL::Video::set_alpha", XS_SDL__Video_set_alpha, file);
        newXS("SDL::Video::get_RGB", XS_SDL__Video_get_RGB, file);
        newXS("SDL::Video::get_RGBA", XS_SDL__Video_get_RGBA, file);
        newXS("SDL::Video::load_BMP", XS_SDL__Video_load_BMP, file);
        newXS("SDL::Video::save_BMP", XS_SDL__Video_save_BMP, file);
        newXS("SDL::Video::fill_rect", XS_SDL__Video_fill_rect, file);
        newXS("SDL::Video::blit_surface", XS_SDL__Video_blit_surface, file);
        newXS("SDL::Video::set_clip_rect", XS_SDL__Video_set_clip_rect, file);
        newXS("SDL::Video::get_clip_rect", XS_SDL__Video_get_clip_rect, file);
        newXS("SDL::Video::lock_YUV_overlay", XS_SDL__Video_lock_YUV_overlay, file);
        newXS("SDL::Video::unlock_YUV_overlay", XS_SDL__Video_unlock_YUV_overlay, file);
        newXS("SDL::Video::display_YUV_overlay", XS_SDL__Video_display_YUV_overlay, file);
        newXS("SDL::Video::GL_load_library", XS_SDL__Video_GL_load_library, file);
        newXS("SDL::Video::GL_get_proc_address", XS_SDL__Video_GL_get_proc_address, file);
        newXS("SDL::Video::GL_set_attribute", XS_SDL__Video_GL_set_attribute, file);
        newXS("SDL::Video::GL_get_attribute", XS_SDL__Video_GL_get_attribute, file);
        newXS("SDL::Video::GL_swap_buffers", XS_SDL__Video_GL_swap_buffers, file);

    /* Initialisation Section */

#if XSubPPtmpAAAA
#if XSubPPtmpAAAB
#endif
#if XSubPPtmpAAAC
#endif
#if XSubPPtmpAAAD
#endif
#if XSubPPtmpAAAE
#endif
#endif
#if XSubPPtmpAAAF
#if XSubPPtmpAAAG
#endif
#if XSubPPtmpAAAH
#endif
#if XSubPPtmpAAAI
#endif
#if XSubPPtmpAAAJ
#endif
#if XSubPPtmpAAAK
#endif
#if XSubPPtmpAAAL
#endif
#if XSubPPtmpAAAM
#endif
#if XSubPPtmpAAAN
#endif
#if XSubPPtmpAAAO
#endif
#if XSubPPtmpAAAP
#endif
#if XSubPPtmpAAAQ
#endif
#endif
#line 1483 "lib/SDL/Video.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

