--- #YAML:1.0
name: SDL_Perl
version: 2.1.0
author:
  - David J. Goehrig <DGOEHRIG@cpan.org>
abstract: Simple DirectMedia Layer for Perl
license: lgpl
generated_by: Module::Build version 0.22, without YAML.pm
