---
name: SDL_Perl
version: v2.2.2.1
author:
  - 'David J. Goehrig <DGOEHRIG@cpan.org>'
abstract: Simple DirectMedia Layer for Perl
license: lgpl
resources:
  license: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
build_requires:
  Alien::SDL: 0.01
  Module::Build: 0.22
  Test::Simple: 0.47
  YAML: 0.68
configure_requires:
  Module::Build: 0.34
provides:
  SDL:
    file: lib/SDL.pm
    version: v2.2.2.1
  SDL::App:
    file: lib/SDL/App.pm
  SDL::Cdrom:
    file: lib/SDL/Cdrom.pm
  SDL::Color:
    file: lib/SDL/Color.pm
  SDL::Constants:
    file: lib/SDL/Constants.pm
  SDL::Cursor:
    file: lib/SDL/Cursor.pm
  SDL::Event:
    file: lib/SDL/Event.pm
  SDL::Font:
    file: lib/SDL/Font.pm
  SDL::MPEG:
    file: lib/SDL/MPEG.pm
  SDL::Mixer:
    file: lib/SDL/Mixer.pm
  SDL::Music:
    file: lib/SDL/Music.pm
  SDL::OpenGL:
    file: lib/SDL/OpenGL.pm
  SDL::OpenGL::Constants:
    file: lib/SDL/OpenGL/Constants.pm
  SDL::Palette:
    file: lib/SDL/Palette.pm
  SDL::Rect:
    file: lib/SDL/Rect.pm
  SDL::SFont:
    file: lib/SDL/SFont.pm
  SDL::Sound:
    file: lib/SDL/Sound.pm
  SDL::Surface:
    file: lib/SDL/Surface.pm
  SDL::TTFont:
    file: lib/SDL/TTFont.pm
  SDL::Timer:
    file: lib/SDL/Timer.pm
  SDL::Tool::Font:
    file: lib/SDL/Tool/Font.pm
  SDL::Tool::Graphic:
    file: lib/SDL/Tool/Graphic.pm
  SDL::Tutorial:
    file: lib/SDL/Tutorial.pm
  SDL::Tutorial::Animation:
    file: lib/SDL/Tutorial/Animation.pm
  SDL::Tutorial::Drawing:
    file: lib/SDL/Tutorial/Drawing.pm
  SDL::Tutorial::Images:
    file: lib/SDL/Tutorial/Images.pm
  SDL::Video:
    file: lib/SDL/Video.pm
  SDL_perl:
    file: lib/SDL_perl.pm
  Walker:
    file: lib/SDL/Tutorial/Images.pm
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
no_index:
  file:
    - make/lib/SDL/Build.pm
    - make/lib/SDL/Utility.pm
    - make/lib/SDL/Build/Cygwin.pm
    - make/lib/SDL/Build/Darwin.pm
    - make/lib/SDL/Build/Freebsd.pm
    - make/lib/SDL/Build/Linux.pm
    - make/lib/SDL/Build/MSWin32.pm
    - make/lib/SDL/Build/Netbsd.pm
    - make/lib/SDL/Build/Openbsd.pm
    - make/lib/SDL/Build/Solaris.pm
    - make/lib/ExtUtils/CBuilder/Platform
    - make/lib/ExtUtils/CBuilder
    - make/lib/ExtUtils/CBuilder/Platform/Windows.pm
