#!/usr/bin/env perl

undef $/;
open FP, "< $ARGV[0]" or die "Couldn't read $ARGV[0]\n";
my $text =  <FP>;
close FP;

$/ = "";

my @xsubs = split "\n\n", $text;

for (@xsubs) 
{
	my @lines = split "\n", $_;

	for $i ( 0 .. @lines ) {
		if ( $lines[$i] =~ /^([^\s].*)\(.*\)/ ) {
			print $1,"\n";
			last;
		}
	}
}
